// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function Greet(arg1:string):Promise<string>;

export function ReadProfileJSON():Promise<string>;

export function ReadSettingsJSON():Promise<string>;

export function WriteProfileJSON(arg1:string):Promise<void>;

export function WriteSettingsJSON(arg1:string):Promise<void>;
