// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function Greet(arg1) {
  return window['go']['main']['App']['Greet'](arg1);
}

export function ReadProfileJSON() {
  return window['go']['main']['App']['ReadProfileJSON']();
}

export function ReadSettingsJSON() {
  return window['go']['main']['App']['ReadSettingsJSON']();
}

export function WriteProfileJSON(arg1) {
  return window['go']['main']['App']['WriteProfileJSON'](arg1);
}

export function WriteSettingsJSON(arg1) {
  return window['go']['main']['App']['WriteSettingsJSON'](arg1);
}
